#  
# -------------------------------------------------- #
#  
#                ${artifactId} v${project.version}
#  
# -------------------------------------------------- #
#  
#  settings:
#    use-packets: if your server accept multiple
#        versions of Minecraft, without ViaVersion
#        or ProtocolSupport, set it to true
#    date-format: language for date formatting
#        like "en" or "de", or a date format
#        according to http://bit.ly/DateFormat
#  
#  messages:
#    contains all messages, use "&" for colors
#    to disable a message, set it to ""
#  
#  versions:
#    contains version name and their protocol
#  
# -------------------------------------------------- #
#  
settings:
  use-packets: false
  date-format: "default"
messages:
  prefix: "&9[ClientStats] &f"
  subline: "&f"
  commands:
    help:
      title: "Commands:"
      stats: "&b/{1} stats &f- Global statistics"
      version: "&b/{1} version &f- Version of players who joined"
      online: "&b/{1} online &f- Version of online players"
      player: "&b/{1} player [who] &f- Version of player"
      reset: "&b/{1} reset &f- Reset tracked stats"
      reload: "&b/{1} reload &f- Reload configuration"
    stats:
      title: "Statistics since {1}:"
      unique: "&b{1}&f unique players joined the server."
      new: "&b{1}&f new players joined it."
      total: "&b{1}&f total connections were made."
      max: "Maximum online players: &b{1}&f (registered: {2})"
      playtime: "Average playtime: &b{1}&f minutes and {2} seconds."
    version:
      title: "Version of players who joined:"
      list: "&f- &a{1}&f players use version {2} (&b{3}%&f)"
      empty: "Nobody joined the server yet."
    online:
      title: "Version of online players:"
      list: "&f- &a{1}&f players use version {2} (&b{3}%&f)"
      empty: "Nobody is currently online."
    player:
      self: "You are using Minecraft &a{1}&f."
      other: "{1} is using &a{2}&f."
      not-found: "Player &c{1}&f wasn't found."
    reset: "All stats have been reset !"
    reload: "Configuration reloaded !"
  warning:
    version-disabled: "Sorry, version detection is §cdisabled§f. Please check server logs for more information."
    exempted: "You are excluded since you have &eclientstats.exempt&f permission."
  error:
    permission: "You don't have the permission."
    not-a-player: "You aren't a player."
    general: "An error occured.."
versions:
  "0": "Unknown"
  "315": "1.11"
  "314": "1.11-pre1"
  "313": "16w43a, 16w44a"
  "312": "16w42a"
  "311": "16w41a"
  "310": "16w40a"
  "309": "16w39c"
  "308": "16w39b"
  "307": "16w39a"
  "306": "16w38a"
  "305": "16w36a"
  "304": "16w35a"
  "303": "16w33a"
  "302": "16w32b"
  "301": "16w32a"
  "210": "1.10 - 1.10.2"
  "205": "1.10-pre2"
  "204": "1.10-pre1"
  "203": "16w21b"
  "202": "16w21a"
  "201": "16w20a"
  "110": "1.9.3, 1.9.4"
  "109": "1.9.2"
  "108": "1.9.1"
  "107": "1.9"
  "106": "1.9 pre4"
  "105": "1.9 pre3"
  "104": "1.9 pre2"
  "103": "1.9 pre1"
  "102": "16w07b"
  "101": "16w07a"
  "100": "16w06a"
  "99": "16w05b"
  "98": "16w05a"
  "97": "16w04a"
  "96": "16w03a"
  "95": "16w02a"
  "94": "15w51b"
  "93": "15w51a"
  "92": "15w50a"
  "91": "15w49b"
  "90": "15w49a"
  "89": "15w47c"
  "88": "15w47b"
  "87": "15w47a"
  "86": "15w46a"
  "85": "15w45a"
  "84": "15w44b"
  "83": "15w44a"
  "82": "15w43c"
  "81": "15w43b"
  "80": "15w43a"
  "79": "15w42a"
  "78": "15w41b"
  "77": "15w41a"
  "76": "15w40b"
  "75": "15w40a"
  "74": "15w39c"
  "73": "15w38b"
  "72": "15w38a"
  "71": "15w37a"
  "70": "15w36d"
  "69": "15w36c"
  "68": "15w36b"
  "67": "15w36a"
  "66": "15w35e"
  "65": "15w35d"
  "64": "15w35c"
  "63": "15w35b"
  "62": "15w35a"
  "61": "15w34d"
  "60": "15w34c"
  "59": "15w34b"
  "58": "15w34a"
  "57": "15w33c"
  "56": "15w33b"
  "55": "15w33a"
  "54": "15w32c"
  "53": "15w32b"
  "52": "15w32a"
  "51": "15w31c"
  "50": "15w31b"
  "49": "15w31a"
  "48": "15w14a"
  "47": "1.8 - 1.8.9"
  "46": "1.8 pre3"
  "45": "1.8 pre2"
  "44": "1.8 pre1"
  "43": "14w34d"
  "42": "14w34c"
  "41": "14w34b"
  "40": "14w34a"
  "39": "14w33c"
  "38": "14w33b"
  "37": "14w33a"
  "36": "14w32d"
  "35": "14w32c"
  "34": "14w32b"
  "33": "14w32a"
  "32": "14w31a"
  "31": "14w30c"
  "30": "14w30a"
  "29": "14w29a"
  "28": "14w28b"
  "27": "14w28a"
  "26": "14w27a, 14w27b"
  "25": "14w26c"
  "24": "14w26b"
  "23": "14w26a"
  "22": "14w25b"
  "21": "14w25a"
  "20": "14w21b"
  "19": "14w21a"
  "18": "14w20a"
  "17": "14w19a"
  "16": "14w18b"
  "15": "14w17a"
  "14": "14w11a"
  "12": "14w08a"
  "11": "14w07a"
  "10": "14w06a"
  "9": "14w05a"
  "8": "14w04b"
  "7": "14w04a"
  "6": "14w03a"
  "5": "1.7.6 - 1.7.10"
  "4": "1.7.1 - 1.7.5"
